<?php 
return array(
    // type
    'log_event' => 1,
    'log_type' => 2,
    'log_comment' => 3,
    'log_user' => 4,
    'log_event_commission' => 5,
    'log_event_complete' => 6,
    'log_shopping_list' => 7,
    'log_estimates' => 8,
    'log_repetition' => 9,
    'log_event_attendance' => 10,
    'log_system_error' => 11,
    'log_event_detail' => 12,
    // log_type
    'log_action_add' => 1,
    'log_action_update' => 2,
    'log_action_del' => 3,
    'log_action_attendance' => 4,
    'log_action_vacation' => 5,
    // 更新的日程种类
    'product_list_id' => '购物单ID',
    'partner' => '推广人',
    'amount' => '报价',
    'total' => '物品总量',
    'event_date' => '日程日期',
    'apm' => '时间段',
    'start_time' => '开始时间',
    'end_time' => '结束时间',
    'worktype' => '工作类型',
    'trucks' => '车辆信息',
    'aboutgoods' => '物品情况',
    'carefully' => '特别注意',
    'from_address' => '出发地',
    'from_elevator' => '出发地电梯情况',
    'from_floor' => '出发地楼层',
    'from_btype' => '出发地建筑',
    'to_address' => '目的地',
    'to_elevator' => '目的地电梯情况',
    'to_floor' => '目的地楼层',
    'to_btype' => '目的地建筑',
    'phone' => '电话号码',
    'wechat' => '微信',
    'deposit_jpy' => '定金JPY',
    'deposit_rmb' => '定金RMB',
    'receipted_at' => '定金收款日期',
    'deposit_type' => '定金收款类型',
    'unset' => '未设定',
    'apm1' => '上午',
    'apm2' => '下午',
    'apm3' => '夜间',
    'apm4' => '全天',
    'elevator1' => '电梯',
    'elevator2' => '楼梯',
    'elevator3' => '电梯+楼梯',
    'btype0' => '未设定',
    'btype1' => '团地',
    'btype2' => 'マンション',
    'btype3' => '高级マンション',
    'btype4' => 'アパート',
    'btype5' => '办公楼',
    'btype6' => '一戸建',
    'deposit_type1' => '现金',
    'deposit_type2' => '银行汇款',
    'deposit_type3' => 'PayPay',
);
